config/routes.rb
Rails.application.routes.draw do
  root 'artists#index'
  resources :artists, :songs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
    has_many :songs, dependent: :destroy
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
    def index
        @artists = Artist.all.order('name')
    end

    def show
        @artist = Artist.find(params[:id])
        @songs = @artist.songs 
    end

    def new
        @artist = Artist.new
    end

    def create
        Artist.create(person_params)
        redirect_to artists_path
    end

    def edit
        @artist = Artist.find(params[:id])
    end

    def update
        artist = Artist.find(params[:id])
        artist.update(person_params)

        redirect_to artist
    end

    def destroy
        Artist.find(params[:id]).destroy
        redirect_to artists_path
    end

    private
        def person_params
            params.require(:artist).permit(:name, :albums, :hometown, :img)
        end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
    def new
        @artist = Artist.find(params[:artist_id])
        @song = Song.new
    end

    def create 
        artist = Artist.find(params[:song][:artist_id])
        Song.create(params.require(:song).permit(:title, :genre, :artist_id))
        
        redirect_to artist
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/_form.html.erb
<%= form_for @artist do |f| %>
    <div class="input-field col s6">
        <%= f.label :name, 'Name'%>
        <%= f.text_field :name%>
    </div>
    <div class="input-field col s6">
        <%= f.label :albums, 'Albums' %>
        <%= f.text_field :albums %>
    </div>
    <div class="input-field col s6">
        <%= f.label :hometown, 'Hometown' %>
        <%= f.text_field :hometown %>
    </div>
    <div class="input-field col s6">
        <%= f.label :img, 'Image' %>
        <%= f.text_field :img %>
    </div>
    <%= f.submit "Submit", :class => "btn waves-effect waves-light" %>
  <% end %>

app/views/artists/edit.html.erb
<h1>Edit <%= @artist.name %> </h1>
<%= render 'artists/form' %>

app/views/artists/index.html.erb
<h1>All the Artists</h1>
<%= link_to "Add an Artist", new_artist_path, { :class => "button waves-effect waves-light btn" } %>
<br><br>

<table class="striped bordered">
  <tr>
    <th>Artist</th>
    <th>Image</th>
    <th>Albums</th>
    <th>Hometown</th>
    <th>Edit</th>
    <th>Delete</th>
  </tr>

  <% @artists.each do |artist| %>
      <tr>
        <td><%= link_to artist.name, artist_path(artist) %></td>
        <td><%= image_tag(artist.img, size: "100x100", alt: "Artist Image") %></td>
        <td><%= artist.albums %></td>
        <td><%= artist.hometown %></td>
        <td><a class="btn-floating btn-large red" href="<%= edit_artist_path(artist) %>" >
      				<i class="large material-icons">mode_edit</i>
    			</a>
    	  </td>
        <td><a class="btn-floating btn-large red" data-confirm="Are you sure you want to delete <%= artist.name %>?" data-method="delete" href="/artists/<%= artist.id %>" rel="nofollow"><i class="large material-icons">Delete Artist</i>
    	   </a>
        </td>
      </tr>
  <% end %>
</table>

app/views/artists/new.html.erb
<h1>New Artist</h1>

<%= render 'artists/form' %>

app/views/artists/show.html.erb
<h1><%= @artist.name %> Songs</h1>
<%= link_to "New Song", new_song_path(:artist_id => @artist.id), { :class => "button waves-effect waves-light btn" } %>
<br><br>

<div class="row">
  <% @songs.each do |song| %>

      <div class="card-panel grey lighten-2 col s4" style="margin: 10px">
        <%= image_tag(@artist.img, size: "100x100", alt: "Artist Image") %>
        <br>
        <strong><%= link_to song.title %></strong>
        <em><%= song.genre %></em>
      </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Muse</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/songs/_form.html.erb
<%= form_for @song do |f| %>
    <%= f.hidden_field :artist_id, :value => @artist.id %>
    <div class="input-field col s6">
        <%= f.label :title, 'Title' %>
        <%= f.text_field :title %>
    </div>
    <div class="input-field col s6">
        <%= f.label :genre, 'Genre' %>
        <%= f.text_field :genre %>
    </div>
    <%= f.submit "Submit", :class => "btn waves-effect waves-light" %>
  <% end %>

app/views/songs/new.html.erb
<h1>New Song for <%= @artist.name %></h1>

<%= render 'songs/form' %>